/// <summary>
/// Holds all pre-written narration strings for the anatomy tutor.
///
/// These are the fixed lines the AI agent speaks automatically at scene
/// transitions and key moments. They are not generated by OpenAI — they are
/// spoken directly through TTS via AITutor.SpeakNarration().
///
/// Every line here is prefetched into AITutor's audio cache at startup
/// (see AITutor.PrefetchAllNarrations()), so scene transitions play instantly
/// from cache instead of hitting the network. Any new scene added to
/// AnatomySceneId should get a line here AND be added to that prefetch list.
///
/// `Trailhead` doubles as the game's cinematic opening — it's the first line
/// SceneNarrationController ever speaks (the flow entry for _MountainTrail at
/// checkpoint 0 maps to AnatomySceneId.Trailhead), so it's where Carla
/// introduces herself and the premise, not just where the Trailhead scene's
/// own content lives.
///
/// Full flow (see AnatomySceneId for the canonical order):
///   Trailhead → Nervous → Skeletal → SteepIncline → Muscular → Circulatory
///   → ThinAir → Respiratory → EnergyCrash → Digestive → Summit
///   → Homeostasis → Completion
///
/// Muscular, ThinAir, EnergyCrash, and Completion below are first-draft
/// placeholders — written to match tone/length of the existing lines, but
/// meant to be rewritten, not treated as final copy.
///
/// This is the single file to edit for all narration copy.
/// No Unity dependencies, no logic — strings only.
/// </summary>
public static class NarrationLines
{
    // ── Scene introductions ──────────────────────────────────────────────────

    public static readonly string Trailhead =
        "Hi — I'm Carla, and I'll be climbing this mountain with you. " +
        "Welcome to Mount Timpanogos. What you're about to do here, we call the Summit Challenge: " +
        "getting to the top while your own body does everything it takes to get you there. " +
        "You're made of trillions of tiny cells, and right now, groups of those cells are teaming up as tissues, " +
        "those tissues are built into organs, and those organs are organized into whole systems — " +
        "all of them about to work together so you can make this climb. " +
        "Here's the important part: I'm not just here to narrate. If you ever wonder what something is, or why " +
        "your body is doing what it's doing, just ask me out loud, any time — I'm listening the whole way up, " +
        "and I'll answer. " +
        "Right now, before your very first step, your brain is already sending a signal down your spinal cord, " +
        "and your skeleton is locking your joints into place so you don't stumble. " +
        "Trace the spine gesture with me, then look for the glowing neurons — that's your nervous system saying 'go.'";

    public static readonly string Nervous =
        "Even before your first step, your brain sends an electrical signal down your spinal cord to your legs — think of it like a text message telling your muscles it's time to move. " +
        "Trace the signal with me, then look for the glowing neurons.";

    public static readonly string Skeletal =
        "Before your leg can move, your skeletal system has to lock your joints into place. Without your bones providing that structure, your muscles would have nothing to pull against. " +
        "Watch the knee joints lock as you take your first step.";

    public static readonly string SteepIncline =
        "Feel that? Your legs are working harder. Your heart is beating faster. Your body knows the demand has increased, and every system is responding. " +
        "Keep climbing — you're about to see exactly what's happening inside.";

    public static readonly string Muscular =
        "This is muscle tissue, up close. Each fiber contracts and pulls on the tendon it's attached to, and that pull is what drags your bones forward with every stride. " +
        "Pull the fibers with me and watch the leg drive against the slope.";

    public static readonly string Circulatory =
        "This is your heart. It is a pump, not a factory, and each squeeze sends blood toward the lungs and the legs at the same time. " +
        "Pump with both hands and watch the oxygen arrive where the muscles need it.";

    public static readonly string ThinAir =
        "Notice your breathing? The air up here has less oxygen in it, so your lungs have to work harder just to deliver the same amount your muscles are asking for. " +
        "Keep climbing — we're about to go see exactly how your lungs are keeping up.";

    public static readonly string Respiratory =
        "Now we are inside the lungs. The diaphragm moves downward to make room for air, and the alveoli move oxygen into the blood before it heads back to the heart. " +
        "Breathing and circulation work as one loop.";

    public static readonly string EnergyCrash =
        "Feeling that heaviness in your legs? Your blood sugar is dropping — your muscles have been burning fuel this whole climb, and now your body is telling you it needs more. " +
        "Let's go find out where that fuel actually comes from.";

    public static readonly string Digestive =
        "Most digestion does not happen in the stomach. The small intestine is where nutrients move into the bloodstream so the muscles can keep climbing. " +
        "Use peristalsis, then pull the glucose through the wall into the blood.";

    public static readonly string Summit =
        "Excellent work. Every step up this mountain depended on your muscles, bones, lungs, heart, brain, and digestive system working together. " +
        "No single body system could have completed the climb alone, and now your body is returning to homeostasis.";

    public static readonly string Homeostasis =
        "Your heart rate is settling, your breathing is evening out, and your body is finding balance again. That is homeostasis.";

    public static readonly string Completion =
        "That's the Summit Challenge. Muscular, skeletal, nervous, circulatory, respiratory, and digestive — six systems, one climb, and your body brought all of them back into balance. " +
        "Great work today.";

    public static string GetSceneNarration(AnatomySceneId sceneId)
    {
        switch (sceneId)
        {
            case AnatomySceneId.Trailhead:    return Trailhead;
            case AnatomySceneId.Nervous:      return Nervous;
            case AnatomySceneId.Skeletal:     return Skeletal;
            case AnatomySceneId.SteepIncline: return SteepIncline;
            case AnatomySceneId.Muscular:     return Muscular;
            case AnatomySceneId.Circulatory:  return Circulatory;
            case AnatomySceneId.ThinAir:      return ThinAir;
            case AnatomySceneId.Respiratory:  return Respiratory;
            case AnatomySceneId.EnergyCrash:  return EnergyCrash;
            case AnatomySceneId.Digestive:    return Digestive;
            case AnatomySceneId.Summit:       return Summit;
            case AnatomySceneId.Homeostasis:  return Homeostasis;
            case AnatomySceneId.Completion:
            default:                          return Completion;
        }
    }
}