/// <summary>
/// Holds all pre-written narration strings for the anatomy tutor.
///
/// These are the fixed lines the AI agent speaks automatically at scene
/// transitions and key moments. They are not generated by OpenAI — they are
/// spoken directly through TTS via AITutor.SpeakNarration().
///
/// Every line here is prefetched into AITutor's audio cache at startup
/// (see AITutor.PrefetchAllNarrations()), so scene transitions play instantly
/// from cache instead of hitting the network. Any new scene added to
/// AnatomySceneId should get a line here AND be added to that prefetch list.
///
/// This is the single file to edit for all narration copy.
/// No Unity dependencies, no logic — strings only.
/// </summary>
public static class NarrationLines
{
    // ── Scene introductions ──────────────────────────────────────────────────

    public static readonly string Intro =
        "Welcome to Mount Timpanogos. Today you will climb the trail and discover what your body is doing to keep you moving. " +
        "Before your first step, the brain sends a signal down the spinal cord and the skeleton locks the joints into place. " +
        "Trace the spine gesture with me, then look for the glowing neurons.";

    public static readonly string Trailhead =
        "The trail is steep, but your nervous system is already working. Your brain sends the go signal, and your skeleton gives your muscles a stable frame to pull against. " +
        "Now look at the glowing neurons and watch the signal move.";

    public static readonly string Nervous =
        "Even before your first step, your brain sends an electrical signal down your spinal cord to your legs — think of it like a text message telling your muscles it's time to move. " +
        "Trace the signal with me, then look for the glowing neurons.";

    public static readonly string Skeletal =
        "Before your leg can move, your skeletal system has to lock your joints into place. Without your bones providing that structure, your muscles would have nothing to pull against. " +
        "Watch the knee joints lock as you take your first step.";

    public static readonly string SteepIncline =
        "Feel that? Your legs are working harder. Your heart is beating faster. Your body knows the demand has increased, and every system is responding. " +
        "Keep climbing — you're about to see exactly what's happening inside.";

    public static readonly string Circulatory =
        "This is your heart. It is a pump, not a factory, and each squeeze sends blood toward the lungs and the legs at the same time. " +
        "Pump with both hands and watch the oxygen arrive where the muscles need it.";

    public static readonly string Respiratory =
        "Now we are inside the lungs. The diaphragm moves downward to make room for air, and the alveoli move oxygen into the blood before it heads back to the heart. " +
        "Breathing and circulation work as one loop.";

    public static readonly string Digestive =
        "Most digestion does not happen in the stomach. The small intestine is where nutrients move into the bloodstream so the muscles can keep climbing. " +
        "Use peristalsis, then pull the glucose through the wall into the blood.";

    public static readonly string Summit =
        "Excellent work. Every step up this mountain depended on your muscles, bones, lungs, heart, brain, and digestive system working together. " +
        "No single body system could have completed the climb alone, and now your body is returning to homeostasis.";

    public static readonly string Homeostasis =
        "Your heart rate is settling, your breathing is evening out, and your body is finding balance again. That is homeostasis.";

    public static string GetSceneNarration(AnatomySceneId sceneId)
    {
        switch (sceneId)
        {
            case AnatomySceneId.Trailhead:   return Trailhead;
            case AnatomySceneId.Nervous:     return Nervous;
            case AnatomySceneId.Skeletal:    return Skeletal;
            case AnatomySceneId.SteepIncline: return SteepIncline;
            case AnatomySceneId.Circulatory: return Circulatory;
            case AnatomySceneId.Respiratory: return Respiratory;
            case AnatomySceneId.Digestive:   return Digestive;
            case AnatomySceneId.Summit:
            default:                         return Summit;
        }
    }
}