/// <summary>
/// Holds all pre-written narration strings for the anatomy tutor.
///
/// These are the fixed lines the AI agent speaks automatically at scene
/// transitions and key moments. They are not generated by OpenAI — they are
/// spoken directly through TTS via AITutor.SpeakNarration().
///
/// This is the single file to edit for all narration copy.
/// No Unity dependencies, no logic — strings only.
/// </summary>
public static class NarrationLines
{
    // ── Scene introductions ──────────────────────────────────────────────────

    public static readonly string Intro =
        "Welcome to Mount Timpanogos. Today you will climb the trail and discover what your body is doing to keep you moving. " +
        "Before your first step, the brain sends a signal down the spinal cord and the skeleton locks the joints into place. " +
        "Trace the spine gesture with me, then look for the glowing neurons.";

    public static readonly string Trailhead =
        "The trail is steep, but your nervous system is already working. Your brain sends the go signal, and your skeleton gives your muscles a stable frame to pull against. " +
        "Now look at the glowing neurons and watch the signal move.";

    public static readonly string Circulatory =
        "This is your heart. It is a pump, not a factory, and each squeeze sends blood toward the lungs and the legs at the same time. " +
        "Pump with both hands and watch the oxygen arrive where the muscles need it.";

    public static readonly string Respiratory =
        "Now we are inside the lungs. The diaphragm moves downward to make room for air, and the alveoli move oxygen into the blood before it heads back to the heart. " +
        "Breathing and circulation work as one loop.";

    public static readonly string Digestive =
        "Most digestion does not happen in the stomach. The small intestine is where nutrients move into the bloodstream so the muscles can keep climbing. " +
        "Use peristalsis, then pull the glucose through the wall into the blood.";

    public static readonly string Summit =
        "Excellent work. Every step up this mountain depended on your muscles, bones, lungs, heart, brain, and digestive system working together. " +
        "No single body system could have completed the climb alone, and now your body is returning to homeostasis.";

    public static readonly string Homeostasis =
        "Your heart rate is settling, your breathing is evening out, and your body is finding balance again. That is homeostasis.";

    public static string GetSceneNarration(AnatomySceneId sceneId)
    {
        switch (sceneId)
        {
            case AnatomySceneId.Trailhead:   return Trailhead;
            case AnatomySceneId.Circulatory:  return Circulatory;
            case AnatomySceneId.Respiratory:  return Respiratory;
            case AnatomySceneId.Digestive:    return Digestive;
            case AnatomySceneId.Summit:
            default:                          return Summit;
        }
    }

}