/// <summary>
/// Holds all pre-written narration strings for the anatomy tutor.
///
/// These are the fixed lines the AI agent speaks automatically at scene
/// transitions and key moments. They are not generated by OpenAI — they are
/// spoken directly through TTS via AITutor.SpeakNarration().
///
/// Every line here is prefetched into AITutor's audio cache at startup
/// (see AITutor.PrefetchAllNarrations()), so scene transitions play instantly
/// from cache instead of hitting the network. Any new scene added to
/// AnatomySceneId should get a line here AND be added to that prefetch list.
///
/// `Trailhead` doubles as the game's cinematic opening — it's the first line
/// SceneNarrationController ever speaks (the flow entry for _MountainTrail at
/// checkpoint 0 maps to AnatomySceneId.Trailhead), so it's where Carla
/// introduces herself and the premise, not just where the Trailhead scene's
/// own content lives.
///
/// Full flow (see AnatomySceneId for the canonical order):
///   Trailhead → Nervous → Skeletal → SteepIncline → Muscular → Circulatory
///   → ThinAir → Respiratory → EnergyCrash → Digestive → Summit
///   → Homeostasis → Completion
///
/// IMPORTANT — the 7 mini-game scenes (Nervous, Skeletal, Muscular,
/// Circulatory, Respiratory, Digestive, Homeostasis) do NOT get the old
/// descriptive/gesture-instruction narration anymore. Each one's constant
/// below IS its Socratic dialogue's Articulate Initial opening question —
/// nothing else plays on entry. Whatever calls
/// SpeakNarration(GetSceneNarration(sceneId)) on scene load (SceneFlowController)
/// needs no changes: it already speaks whatever these constants return, and
/// that's now the question itself. Everything the student says in reply is
/// what goes through SocraticDialogueController / AIResponseGenerator's
/// assessed pipeline. The mountain-trail narrative beats (Trailhead,
/// SteepIncline, ThinAir, EnergyCrash, Summit, Completion) are untouched —
/// they have no mini-game attached and keep their full descriptive narration.
///
/// ThinAir, EnergyCrash, and Completion below are still first-draft
/// placeholders — written to match tone/length of the existing lines, but
/// meant to be rewritten, not treated as final copy.
///
/// This is the single file to edit for all narration copy.
/// No Unity dependencies, no logic — strings only.
/// </summary>
public static class NarrationLines
{
    // ── Mountain-trail narrative beats (no mini-game — unchanged) ───────────

    public static readonly string Trailhead =
        "Hi — I'm Carla, and I'll be climbing this mountain with you. " +
        "Welcome to Mount Timpanogos. What you're about to do here, we call the Summit Challenge: " +
        "getting to the top while your own body does everything it takes to get you there. " +
        "You're made of trillions of tiny cells, and right now, groups of those cells are teaming up as tissues, " +
        "those tissues are built into organs, and those organs are organized into whole systems — " +
        "all of them about to work together so you can make this climb. " +
        "If you ever wonder what something is, or why " +
        "your body is doing what it's doing, just ask me out loud at any time — I'm listening the whole way up, " +
        "and I'll answer. " +
        "First we will explore the nervous system and explore what needs to happen before your very first step. ";

    public static readonly string SteepIncline =
        "Your knee just locked into place, and this trail is about to get steeper. " +
        "That means your legs have to work harder. " +
        "You're about to see how your muscles and heart are responding to this challenge.";

    public static readonly string ThinAir =
        "Notice your breathing? The air up here has less oxygen in it, so your lungs have to work harder just to deliver the same amount your muscles are asking for. " +
        "Keep climbing — we're about to go see exactly how your lungs are keeping up.";

    public static readonly string EnergyCrash =
        "Feeling that heaviness in your legs? Your blood sugar is dropping — your muscles have been burning fuel this whole climb, and now your body is telling you it needs more. " +
        "Let's go find out where that fuel actually comes from.";

    public static readonly string Summit =
        "Excellent work. Every step up this mountain depended on your muscles, bones, lungs, heart, brain, and digestive system working together. " +
        "No single body system could have completed the climb alone, and now your body is returning to homeostasis.";

    public static readonly string Completion =
        "That's the Summit Challenge. Muscular, skeletal, nervous, circulatory, respiratory, and digestive — six systems, one climb, and your body brought all of them back into balance. " +
        "Great work today.";

    // ── Mini-game Socratic dialogue starting questions ──────────────────────
    // These ARE the mini-game scene's entire narration now — see the class
    // doc above. Deliberately broad/observational, not "how does this work"
    // — see SocraticDialogueController's ArticulateInitial instructions for
    // why: the AI bridges from "what do you see" to mechanism itself, so
    // the very first question a student hears is one they can't get wrong.
    // First-draft copy, meant to be rewritten to the professor's exact
    // wording, not treated as final.

    public static readonly string Nervous =
        "Take a look around — what do you see in front of you?";

    public static readonly string Skeletal =
        "What does this part of the skeleton look like to you?";

    public static readonly string Muscular =
        "Take a close look — what do you see here inside the leg?";

    public static readonly string Circulatory =
        "What do you see in front of you right now?";

    public static readonly string Respiratory =
        "Look around — what do you notice in here?";

    public static readonly string Digestive =
        "What does it look like where you're standing right now?";

    public static readonly string Homeostasis =
        "Take a look at the dashboard in front of you — what do you notice?";

    public static string GetSceneNarration(AnatomySceneId sceneId)
    {
        switch (sceneId)
        {
            case AnatomySceneId.Trailhead:    return Trailhead;
            case AnatomySceneId.Nervous:      return Nervous;
            case AnatomySceneId.Skeletal:     return Skeletal;
            case AnatomySceneId.SteepIncline: return SteepIncline;
            case AnatomySceneId.Muscular:     return Muscular;
            case AnatomySceneId.Circulatory:  return Circulatory;
            case AnatomySceneId.ThinAir:      return ThinAir;
            case AnatomySceneId.Respiratory:  return Respiratory;
            case AnatomySceneId.EnergyCrash:  return EnergyCrash;
            case AnatomySceneId.Digestive:    return Digestive;
            case AnatomySceneId.Summit:       return Summit;
            case AnatomySceneId.Homeostasis:  return Homeostasis;
            case AnatomySceneId.Completion:
            default:                          return Completion;
        }
    }
}